---
jenkins:
  mode: NORMAL
  numExecutors: 0
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  scmCheckoutRetryCount: 3
  labelString: "master"

  nodes:
    - permanent:
        labelString: "slave"
        launcher:
          jnlp:
            workDirSettings:
              disabled: false
              workDirPath: "/home/jenkins/agent/"
        name: "slave-1"
        numExecutors: 1
        remoteFS: "/home/jenkins/.jenkins/"
    - permanent:
        labelString: "slave"
        launcher:
          jnlp:
            workDirSettings:
              disabled: false
              workDirPath: "/home/jenkins/agent/"
        name: "slave-2"
        numExecutors: 1
        remoteFS: "/home/jenkins/.jenkins/"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: ${admin_password}

  projectNamingStrategy:
    pattern:
      description: "Restrict project names to alphanumeric characters"
      forceExistingJobs: true
      namePattern: "[a-zA-Z0-9_-]{3,}"

#  crumbIssuer: "standard"

#  remotingSecurity:
#    enabled: true

# credentials:
#   system:
#     domainCredentials:
#       - credentials:
#         - usernamePassword:
#           scope: GLOBAL
#           id: github-user
#           username: ewelina
#           password: ${github:-githubPassw0rd}
#           description: github username/password

tool:
  git:
    installations:
      - name: "Default"
        home: "git"
