---
jenkins:
  mode: NORMAL
  numExecutors: 0
  scmCheckoutRetryCount: 3
  labelString: "master"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: ${admin_password}

  projectNamingStrategy:
    pattern:
      description: "Restrict project names to alphanumeric characters"
      forceExistingJobs: true
      namePattern: "[a-zA-Z0-9_-]{3,}"

#  crumbIssuer: "standard"

#  remotingSecurity:
#    enabled: true

# credentials:
#   system:
#     domainCredentials:
#       - credentials:
#         - usernamePassword:
#           scope: GLOBAL
#           id: github-user
#           username: ewelina
#           password: ${github:-githubPassw0rd}
#           description: github username/password

tool:
  git:
    installations:
      - name: "Default"
        home: "git"
