---
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  slaveAgentPort: 50000
  nodes:
    - permanent:
        labelString: "slave"
        launcher:
          jnlp:
            workDirSettings:
              disabled: false
              workDirPath: "/home/jenkins/agent/"
        name: "slave-1"
        numExecutors: 1
        remoteFS: "/home/jenkins/.jenkins/"
    - permanent:
        labelString: "slave"
        launcher:
          jnlp:
            workDirSettings:
              disabled: false
              workDirPath: "/home/jenkins/agent/"
        name: "slave-2"
        numExecutors: 1
        remoteFS: "/home/jenkins/.jenkins/"
