---
jenkins:
  authorizationStrategy:
    projectMatrix:
      permissions:
        - "Agent/Connect:authenticated"
        - "Agent/Disconnect:authenticated"
        - "Credentials/View:authenticated"
        - "Job/Build:authenticated"
        - "Job/Cancel:authenticated"
        - "Job/Configure:authenticated"
        - "Job/Create:authenticated"
        - "Job/Delete:authenticated"
        - "Job/Discover:authenticated"
        - "Job/Move:authenticated"
        - "Job/Read:anonymous"
        - "Job/Read:authenticated"
        - "Job/Workspace:authenticated"
        - "Lockable Resources/Reserve:authenticated"
        - "Lockable Resources/Unlock:authenticated"
        - "Lockable Resources/View:anonymous"
        - "Lockable Resources/View:authenticated"
        - "Overall/Administer:admin"
        - "Overall/Read:anonymous"
        - "Overall/Read:authenticated"
        - "Run/Delete:authenticated"
        - "Run/Replay:authenticated"
        - "Run/Update:authenticated"
        - "SCM/Tag:authenticated"
        - "View/Configure:authenticated"
        - "View/Create:authenticated"
        - "View/Delete:authenticated"
        - "View/Read:anonymous"
        - "View/Read:authenticated"
