---
credentials:
  system:
    domainCredentials:
      - domain:
          name: "docker-cloud"
        credentials:
          - usernamePassword:
              description: "skarzi docker hub credentials"
              id: "docker_hub__skarzi"
              username: "skarzi"
              password: "${docker_hub__skarzi}"
              scope: GLOBAL

jenkins:
  clouds:
    - docker:
        dockerApi:
          connectTimeout: 60
          dockerHost:
            uri: "unix:///var/run/docker.sock"
          readTimeout: 60
        exposeDockerHost: true
        name: "docker-cloud"
        templates:
          - connector:
              attach:
                user: "jenkins"
            dockerTemplateBase:
              image: "skarzi/jenkins-slave-dood"
              pullCredentialsId: "docker_hub__skarzi"
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock"
              volumesString: "/var/run/docker.sock:/var/run/docker.sock"
            instanceCapStr: "10"
            labelString: "docker docker-dood slave-dood"
            name: "slave__dood"
            pullTimeout: 300
            remoteFs: "/home/jenkins/"
