---
advisor:
  acceptToS: true
  email: "me@skarzi.com"
  excludedComponents:
    - "Agents"
    - "AgentsConfigFile"
    - "ConfigFileComponent"
    - "RootCAs"
    - "SlaveLogs"
    - "OtherConfigFilesComponent"
  nagDisabled: false
