---
version: '3.8'
services:
  master:
    container_name: jenkins-master
    build:
      context: .
      dockerfile: ./docker/master/Dockerfile
    env_file:
      - .envs/.production/.master
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
    ports:
      # web interface
      - "8989:8080"
      # port to communicate with JNLP agents
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./config/casc/:/var/jenkins_conf/
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - admin_password
      - delfina_password
    healthcheck:
      # NOTE: `/login/` is requested, because it doesn't require
      # authorization, other possibility is e.g. `/robots.txt`.
      # `$$` is used here to escape `$`
      test: |
        /usr/bin/test $$(
          /usr/bin/curl \
            --fail http://$${VIRTUAL_HOST}/login \
            --write-out "%{http_code}" \
            --silent \
            --output /dev/null
        ) -eq 200
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 2m


  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      # TODO: support SSL/TLS
      - /var/run/docker.sock:/tmp/docker.sock:ro

secrets:
  # users
  admin_password:
    file: ./.secrets/admin_password
  delfina_password:
    file: ./.secrets/delfina_password
  # docker cloud
  skarzi_docker_hub_password:
    file: ./.secrets/skarzi_docker_hub_password

volumes:
  jenkins_home:
