---
name: depup
on:
  workflow_dispatch: {}
  schedule:
    - cron: '5 4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-depup@v1.2.1
        id: depup
        with:
          file: config/plugins_extra.txt
          version_name: configuration-as-code
          repo: jenkinsci/configuration-as-code-plugin
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: >-
            bump configuration-as-code plugin to
            ${{ steps.depup.outputs.latest }}
          commit-message: >-
            bump configuration-as-code plugin to
            ${{ steps.depup.outputs.latest }}
          body: |
            Update configuration-as-code to
            [${{ steps.depup.outputs.latest }}](
            https://github.com/jenkinsci/configuration-as-code/releases/tag/
            configuration-as-code-${{steps.depup.outputs.latest}})

            This PR is auto generated by
            [depup workflow](
            https://github.com/${{ github.repository }}/actions
            ?query=workflow%3Adepup).
          branch: dependencies/jenkins-plugins/configuration-as-code
          base: master
