---
name: dockerhub
on:
  push:
    branches:
      - master
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup docker tags and labels
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4.1.0
        with:
          tag-sha: true
          images: skarzi/jenkins-slave-dood
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push jenkins dood slave image to DockerHub
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./docker/slave/Dockerfile
          build-args: DOCKER_GID=${{ secrets.DOCKER_GID }}
          cache-from: type=registry,ref=skarzi/jenkins-slave-dood
          cache-to: type=inline
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
