---
name: docker_hub
on:
  push:
    branches:
      - master
  release:
    types:
      - published
jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push jenkins dood slave image to docker hub
        uses: docker/build-push-action@v1
        with:
          context: .
          dockerfile: docker/slave/Dockerfile
          build_args: DOCKER_GID=${{ secrets.DOCKER_GID }}
          cache_froms: skarzi/jenkins-slave-dood
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: skarzi/jenkins-slave-dood
          tag_with_ref: true
