---
name: lint
on:
  - workflow_dispatch
  - push
  - pull_request
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'set up Python 3.8'
        uses: actions/setup-python@v2.3.0
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: lint yaml files
        run: yamllint -c .yamllint.yml -s .

  lint-dotenvs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: find dotenv files to lint
        id: find-dotenvs
        run: |
          _DOTENV_FILES=$(find .envs/.dist -type f | paste -sd ' ')
          echo "::set-output name=dotenv_files::${_DOTENV_FILES}"
      - uses: wemake-services/dotenv-linter@master
        with:
          reporter: 'github-pr-review'
          options: '${{ steps.find-dotenvs.outputs.dotenv_files }}'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

  lint-dockerfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: 'github-pr-review'

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: debug environment variables
        run: env
      - name: debug event json
        run: cat "${GITHUB_EVENT_PATH}"
      - name: lint markdown files
        uses: reviewdog/action-markdownlint@v0.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          fail_on_error: true
