---
name: misspell
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v3.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fixes by misspell-fixer'
          title: 'typos fix by misspell-fixer'
          delete-branch: true
          reviewers: skarzi
